version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:8.0.20
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
            yarn install --pure-lockfile

      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
            - ./node_modules

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run:
          name: Setup DB
          command: |
            mv config/database.ci.yml config/database.yml
            bundle exec rails db:create
            bundle exec rails db:schema:load

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: RSpec
          command: |
            mkdir /tmp/rspec
            bundle exec rspec --color \
                              --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/rspec/rspec.xml

      - store_test_results:
          path: /tmp/rspec

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: /^actions.*/
