version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Copy setteing
          command: cp .env.dev.sample .env.dev
      - run:
          name: Build images
          command: docker-compose build
      - run:
          name: Setup DB
          command: docker-compose run --rm web rails db:create db:migrate
      - run:
          name: Run container
          command: docker-compose up -d
      - run:
          name: Run RSpec
          command: docker-compose run --rm web rspec --color \
                                                    --format progress \
                                                    --format RspecJunitFormatter \
                                                    --out /tmp/spec/rspec.xml
      # - run:
      #     name: run rubocop
      #     command: bundle exec rubocop
      - run:
          name: docker-compose down
          command: docker-compose down
